### ISSUE TITLE
shellcheck.net errors?

### ISSUE THREAD

**Issue by thellum** [trice81384/scripts#8]
Hello, I am keen to use your script in our JAMF instance to upgrade machines from Mojave to Catalina.
However, when I run your "macOSUpgrades_SelfService" script through shellcheck.net, I see reported a number of warnings.
It's likely that I am using the script incorrectly in JAMF. Can you address the shellcheck warnings below?
$ shellcheck myscript
 
Line 49:
    CachedmacOSFile="/Library/Application Support/Jamf/Waiting Room/$PackageName"
    ^-- SC2034: CachedmacOSFile appears unused. Verify use (or export if used externally).
 
Line 83:
   restartIcon="/System/Library/CoreServices/loginwindow.app/Contents/Resources/Restart.png"
   ^-- SC2034: restartIcon appears unused. Verify use (or export if used externally).
 
Line 201:
let Counter="300"
^-- SC2219: Instead of 'let expr', prefer (( expr )) .
 
Line 253:
     disown $jamfHelperUID
            ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
     disown "$jamfHelperUID"
 
Line 268:
disown $jamfHelperUID
       ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
disown "$jamfHelperUID"
 
Line 322:
       userID=$( id -u ${loggedInUser} )
                       ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
       userID=$( id -u "${loggedInUser}" )
 
Line 323:
       launchctl bootstrap gui/${userID} /Library/LaunchAgents/com.apple.install.osinstallersetupd.plist
                               ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
       launchctl bootstrap gui/"${userID}" /Library/LaunchAgents/com.apple.install.osinstallersetupd.plist

$

**Comment by trice81384** [comment]
@thellum you can safely ignore those - its just shellcheck being overly cautious. The script runs ok. 
Also this is being moved to https://github.com/trice81384/JAMF/blob/master/macOSUpdates_SelfService
